studentsdb/urls.py
from django.conf.urls import patterns, include,url
from django.contrib import admin
from .settings import MEDIA_ROOT, DEBUG
from students.view.journal import JournalView
from django.contrib.auth import views as auth_views
from django.views.generic.base import RedirectView, TemplateView
from students.view.student import stud_add, student_edit, student_delete
from students.view.group import groups_add, groups_edit, groups_delete 
from students.view.logs import logs
from students.view.contact_admin import contact_admin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from registration.backends.default import views as registration_views
from log.views import user_edit





js_info_dict = {
'packages': ('students',),
}

urlpatterns = patterns('',
	#journal
url(r'^(?P<pk>\d+)?/?$', login_required(JournalView.as_view()), name='journal'),
# Students urls
url(r'^pupils$', 'students.view.student.students_list', name='main'),
url(r'^pupil_add$', login_required(stud_add), name='s_add'),
url(r'^pupil/(?P<pk>\d+)/edit/$',login_required(student_edit),
name='students_edit'),
url(r'^pupil/(?P<pk>\d+)/delete/$', login_required(student_delete),name='students_delete'),
#Groups urls
url(r'^classes$', 'students.view.group.grup', name='groups'),
url(r'^class_add$', 'students.view.group.groups_add', name='groups_add'),
url(r'^class/(?P<pk>\d+)/edit/$',
'students.view.group.groups_edit', name='groups_edit'),
url(r'^class/(?P<pk>\d+)/delete/$',
'students.view.group.groups_delete', name='groups_delete'),
url(r'^class/(?P<pk>\d+)/one/$',
'students.view.group.groups_one', name='groups_one'),
url(r'^admin/', include(admin.site.urls)),

#logs
url(r'^logs$', login_required(logs), name='logs'),
# Contact Admin Form
url(r'^contact-admin/$', login_required(contact_admin),
name='contact_admin'),
#i18n of js
url(r'^jsi18n.js$', 'django.views.i18n.javascript_catalog', js_info_dict),

# User Related urls
url(r'^users/profile/$', login_required(TemplateView.as_view(
template_name='registration/profile.html')), name='profile'),
url(r'^users/logout/$', auth_views.logout, kwargs={'next_page': 'main'}, name='auth_logout'),
url(r'^register/complete/$', TemplateView.as_view(template_name='registration/confirm_email.html'), name='registration_complete'),
url(r'^users/', include('registration.backends.default.urls', namespace='users')),
url(r'^users/activate/(?P<activation_key>\w+)/$', registration_views.ActivationView.as_view(),
name='registration_activate'),
url(r'^users/activate/complete/$',
TemplateView.as_view(template_name='registration/activation_complete.html'),
name='registration_activation_complete'),
url(r'^users_list$', 'log.views.users_list', name='users_list'),
url(r'^users/(?P<pk>\d+)/one/$',
'log.views.users_one', name='users_one'),
url(r'^prof/(?P<pk>\d+)/edit$', 'log.views.user_edit', name='prof_edit'),
url(r'^user/(?P<pk>\d+)/edit$', 'log.views.user_one_edit', name='user_edit'),
url(r'^activate/complete/$', TemplateView.as_view(template_name='registration/login.html'),
    name='registration_activation_complete'),


url(r'^password_change/$', 'django.contrib.auth.views.password_change', name='password_change'),
url(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', name='password_change_done'),
url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
url(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    'django.contrib.auth.views.password_reset_confirm',
    name='password_reset_confirm'),
url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),


# Social Auth Related urls
url('^social/', include('social.apps.django_app.urls', namespace ='social')),
)

if DEBUG:
 # serve files from media folder
 urlpatterns += patterns('',
 url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
 'document_root': MEDIA_ROOT}))

log/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _

class StProfile(models.Model):


  user = models.OneToOneField(User)
  class Meta(object):
    verbose_name = _(u"User Profile")

  mobile_phone = models.CharField(
    max_length=12,
    blank=True,
    verbose_name=_(u"Mobile Phone"),
  )
  lang = models.CharField(
    max_length=12,
    blank=True,
    verbose_name=_(u"lang"),
  )
  def __unicode__(self):
    return self.user.username






class logentry(models.Model):
  level = models.CharField(
    max_length=20,
    blank=False)
  asctime = models.DateTimeField(
    blank=False,
    null=True)
  module = models.CharField(
    max_length=100,
    blank=False,)
  message = models.TextField(
    blank=False,)
  def __unicode__(self):
    return u"%s %s %s %s" % (self.level, self.asctime, self.module, self.message)

students/models/exam.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
class Exam(models.Model):
  """Exam Model"""
  class Meta(object):
    verbose_name = _(u"Exam")
    verbose_name_plural = _(u"Exams")
  title = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"name"))
  group = models.ForeignKey('Group',
    verbose_name=_(u'Group'),
    blank=False,
    null=True,)

  date = models.DateField(
    blank=True,
    verbose_name=_(u"dates"))
  def __unicode__(self):
    return u"%s %s" % (self.title, self.group)

students/models/group.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
class Group(models.Model):
  """Group Model"""
  class Meta(object):
    verbose_name = _(u"group")
    verbose_name_plural = _(u"groups")
  title = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"name"))
  leader = models.OneToOneField('Student',
    verbose_name=_(u"leader"),
    blank=True,
    null=True,
    on_delete=models.SET_NULL)
  notes = models.TextField(
    blank=True,
    verbose_name=_(u"Additional notes"))
  user_g = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"user"))
  def __unicode__(self):
    return u"%s" % (self.title,)

students/models/log.py
# -*- coding: utf-8 -*-
from django.db import models

students/models/monthjournal.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
class MonthJournal(models.Model):
  
    class Meta:
      verbose_name = _(u'Monthly journal')
      verbose_name_plural = _(u'Monthly journals')
      
    student = models.ForeignKey('Student',
      verbose_name=_(u'Student'),
      blank=False,
      unique_for_month='date')
    date = models.DateField(
      verbose_name=_(u'Date'),
      blank=False)
    user_j = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"user"))
    
    present_day1 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day1"))

    present_day2 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day2"))

    present_day3 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day3"))

    present_day4 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day4"))

    present_day5 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day5"))

    present_day6 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day6"))

    present_day7 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day7"))

    present_day8 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day8"))

    present_day9 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day9"))

    present_day10 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day10"))

    present_day11 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day11"))

    present_day12 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day12"))

    present_day13 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day13"))

    present_day14 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day14"))

    present_day15 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day15"))

    present_day16 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day16"))

    present_day17 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day17"))

    present_day18 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day18"))

    present_day19 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day19"))

    present_day20 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day20"))

    present_day21 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day21"))

    present_day22 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day22"))

    present_day23 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day23"))

    present_day24 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day24"))

    present_day25 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day25"))

    present_day26 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day26"))

    present_day27 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day27"))

    present_day28 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day28"))

    present_day29 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day29"))

    present_day30 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day30"))

    present_day31 = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"present_day31"))

    
   
    def __unicode__(self):
      return u'%s: %d, %d' % (self.student.last_name, self.date.month,
        self.date.year)

students/models/student.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
# Create your models here.
class Student(models.Model):
  #Student Model
  class Meta(object):
    verbose_name = _(u"Student")
    verbose_name_plural = _(u"Students")
  first_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"first_name"))
  last_name = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"last_name"))
  birthday = models.DateField(
    blank=True,
    verbose_name=_(u"birthday"),
    null=True)
  photo = models.ImageField(
    blank=True,
    verbose_name=_(u"photo"),
    null=True)
  ticket = models.CharField(
    max_length=256,
    blank=True,
    verbose_name=_(u"ticket"))
  student_group_id = models.ForeignKey('Group',
    verbose_name=_(u"group"),
    blank=False,
    null=True,
    on_delete=models.PROTECT)
  notes = models.TextField(
    blank=True,
    verbose_name=_(u"Additional notes"))
  user_s = models.CharField(
    max_length=256,
    blank=False,
    verbose_name=_(u"user"))
  
  def __unicode__(self):
    return u"%s %s" % (self.first_name, self.last_name)

log/views.py
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.contrib import messages
from PIL import Image
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required






@permission_required('auth.add_user')
def users_list(request):
	users = User.objects.all()
	return render(request, 'users_list.html',
    {'users': users})







def users_one(request, pk):
   use = User.objects.get(id=pk)
   return render(request, 'user_one_profile.html',
   {'user_one': use})





def user_edit(request, pk):
    use = User.objects.get(pk=pk)
    
    if request.method == "POST":
      data = User.objects.get(pk=pk)
      if request.POST.get('add_button') is not None:

        errors = {}

        username = request.POST.get('username', '').strip()
        if not username:
          errors['username'] = _(u"Name is mandatory.")
        else:
          data.username = username

        password = request.POST.get('password', '').strip()
        if not password:
          errors['password'] = _(u"Name is mandatory.")
        else:
          data.password = password

        email = request.POST.get('email', '').strip()
        if not email:
          errors['email'] = _(u"Name is mandatory.")
        else:
          data.email = email

        if not errors:
          
          data.save()
          return HttpResponseRedirect( u'%s?status_message=%s'  % (reverse('users_list'), _(u'User edited succefully')))
        else:
          # render form with errors and previous user input
          return render(request, 'user_edit.html',
          {'pk': pk,'errors': errors})
      elif request.POST.get('cancel_button') is not None:
        # redirect to home page on cancel button
        return HttpResponseRedirect( u'%s?status_message=%s' % (reverse('users_list'), _('Editing user canceled')))
    else:
     # initial form render
     return render(request, 'user_edit.html',
     {'use': use, 'pk': pk})






def user_one_edit(request, pk):
    use = User.objects.get(pk=pk)
    
    
    if request.method == "POST":
      data = User.objects.get(pk=pk)
      ln = User.objects.get(pk=pk)
      if request.POST.get('add_button') is not None:

        errors = {}

        username = request.POST.get('username', '').strip()
        if not username:
          errors['username'] = _(u"Name is mandatory.")
        else:
          data.username = username

        password = request.POST.get('password', '').strip()
        if not password:
          errors['password'] = _(u"Name is mandatory.")
        else:
          data.password = password

        email = request.POST.get('email', '').strip()
        if not email:
          errors['email'] = _(u"Name is mandatory.")
        else:
          data.email = email

        lang = request.POST.get('lang', '').strip()
        if not lang:
          errors['lang'] = _(u"Language is mandatory")
        else:
          ln.stprofile.lang = lang


        if not errors:
          
          data.save()
          ln.stprofile.save()
          print ln
          return HttpResponseRedirect( u'%s?status_message=%s'  % (reverse('users_list'), _(u'User edited succefully')))
        else:
          # render form with errors and previous user input
          return render(request, 'user_edit.html',
          {'pk': pk,'errors': errors})
      elif request.POST.get('cancel_button') is not None:
        # redirect to home page on cancel button
        return HttpResponseRedirect( u'%s?status_message=%s' % (reverse('users_list'), _('Editing user canceled')))
    else:
     # initial form render
     return render(request, 'user_one_edit.html',
     {'use': use, 'pk': pk})









def user_e(request, pk):
    use = User.objects.get(pk=pk)
    
    
    if request.method == "POST":
      ln = User.objects.get(pk=pk)
      print ln
      if request.POST.get('add_button') is not None:

        errors = {}

        lang = request.POST.get('lang', '').strip()
        if not lang:
          errors['lang'] = _(u"Language is mandatory")
        else:
          ln.stprofile.lang = lang


        if not errors:
          
          ln.stprofile.save()
          print ln
          return HttpResponseRedirect( u'%s?status_message=%s'  % (reverse('users_list'), _(u'User edited succefully')))
        else:
          # render form with errors and previous user input
          return render(request, 'user_edit.html',
          {'pk': pk,'errors': errors})
      elif request.POST.get('cancel_button') is not None:
        # redirect to home page on cancel button
        return HttpResponseRedirect( u'%s?status_message=%s' % (reverse('users_list'), _('Editing user canceled')))
    else:
     # initial form render
     return render(request, 'user_one_edit.html',
     {})

students/templates/students/base.html
{% load i18n %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="uk">
<head>
<meta charset="UTF-8"/>

<meta name="description" value="{% trans "Pupils acounting service of school" %}" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet"
href="https://cdn.jsdelivr.net/bootstrap/3.3.0/css/bootstrap.min.css">
<link rel="stylesheet"
href="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/css/bootstrap-datetimepicker.min.css">
<link rel="stylesheet"
href="{{ PORTAL_URL }}{% static "css/main.css" %}">
{% block extra_css %}{% endblock extra_css %}
</head>
<body>

<!-- Start Container -->
<div class="container">

{% if user.is_authenticated %} 
<div class="col-xs-4" id="lang-selector"> 
<select>
{% if PK %}
<option value="">{{PK}}</option>
{% else %}
<option value="">{% trans "change language" %}</option>
{% endif %}
<option value="uk">українська</option>
<option value="en">english</option>  
</select> 
</div>
{% endif %}

<div id="user-toolbar">
{% if user.is_authenticated %}
<div class="col-xs-7">
   <a href="{% url "profile" %}">{{ user.username }}</a> 
   |
   <a href="{% url "users:auth_logout" %}">{% trans "Logout" %}</a>
</div>
<div class="col-xs-5">
<strong>{% trans "group" %}:</strong> 
<select> 
<option value="">{% trans "all pupils" %}</option>
{% for group in GROUPS %}  
<option value="{{ group.id }}" {% if group.selected %} selected="1" {% endif %}>
  {{ group.title }} {% if group.leader %} {{ group.leader }} {% endif %} 
  {% endfor %}
</option>  
</select> 
</div>
{% endif %}
</div> 
{% if user.is_authenticated %}
<!-- Start Header -->
<div class="row" id="header">
<div class="col-xs-8">
<h1 id="log_title"Start Content Columns>{% trans "Pupils acounting service" %}</h1>
</div>
<!-- End Header -->
<!-- Start subheader -->
<div class="row" id="sub-header">
<div class="col-xs-12">
<ul class="nav nav-tabs" role="tablist">
<li role="presentation" {% if request.path == '/' %}class="active"{% endif %}><a href="{% url "journal" %}">{% trans "visiting" %}</a></li>
<li role="presentation" {% if '/classes' in request.path %}class="active"{% endif %}><a href="{% url "groups" %}">{% trans "classes" %}</a></li>
<li role="presentation" {% if '/pupils' in request.path %}class="active"{% endif %}><a href="{% url "main" %}">{% trans "Pupils" %}</a></li>
<li role="presentation" {% if '/contact-admin' in request.path %}class="active"{% endif %}><a href="{% url "contact_admin" %}">{% trans "to contact" %}</a></li>
{% endif %}
{% if perms.auth.add_user %}
<li role="presentation" {% if '/logs' in request.path %}class="active"{% endif %}><a href="{% url "logs" %}">{% trans "log journal" %}</a></li>
<li role="presentation" {% if '/users_list' in request.path %}class="active"{% endif %}><a href="{% url "users_list" %}">{% trans "list of users" %}</a></li>
</ul>
</div>
</div>
{% endif %}
<!-- End subheader -->
<!-- Start Content Columns -->
<div class="row" id="content-columns">
<div class="col-xs-12" id="content-column">

{% block status_message %}
{% if request.GET.status_message %}
<div class="alert alert-warning" role="alert">{{ request.GET.status_message }}</div>
{% endif %}
{% endblock %}

<h2>{% block title %}{% endblock title %}</h2>
{% block content %}{% endblock content %}
</div>
</div>
{% if user.is_authenticated %}
{% else %}

{% endif %}
<!-- End Content Columns -->

</div>
<!-- End Container -->
<!-- Modal Boilerplate -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog">
<div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal"
aria-label="Close">
<span aria-hidden="true">&times;</span></button>
<h4 class="modal-title" id="myModalLabel"><!-- --></h4>
</div>
<div class="modal-body"><!-- --></div>
<div class="modal-footer"><!-- --></div>
</div>
</div>
</div>
<!-- Javascripts Inclusion -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>
<script src="https://cdn.jsdelivr.net/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.0.0/js/bootstrap-datetimepicker.min.js"></script>
<script src="{% url "django.views.i18n.javascript_catalog" %}""></script>
<script src="{% static "js/main.js" %}"></script>
{% block extra_js %}{% endblock extra_js %}
</body>
</html>

students/templates/students/contact.html
{% extends "students/base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}{% trans "pupils" %}{% endblock meta_title %}
{% block title %}<div id="cont_title">{% trans "conection with administration of site" %}</div>{% endblock title %}
{% block status_message %}
{% if form.errors %}
<div class="alert alert-warning" role="alert">
{% trans "Please, correct next errors!" %}
</div>
{% endif %}
{{ block.super }}
{% endblock %}
<div id="cont_form">
{% block content %}
<div id="cont_form">
{% crispy form %}
</div>
{% endblock content %}

students/templates/students/groups_one_null.html
{% extends "students/base.html" %}
{% load i18n %}
{% load static from staticfiles %}
{% block meta_title %}{% trans "pupils" %}{% endblock meta_title %}
{% block title %} {% trans "group" %} {{group.title}} {% trans "dont contains pupil" %}{% endblock title %}
{% block content %}
{% endblock content %}

students/templates/students/students_add_edit.html
{% extends "students/base.html" %}
{% load i18n %}
{% trans "pupils" %}
{% load static from staticfiles %}
{% load crispy_forms_tags %}
{% block meta_title %}
{% trans "pupils" %}
{% endblock meta_title %}
{% block title %}
{% if student %}
<div id="title_form_edit">{% trans "editing of pupil" %}  {{student.first_name}} {{student.last_name}}</div>
{% else %}
<div id="title_form_add">{% trans "adding of pupil" %}</div>
{% endif %}
{% endblock title %}
{% block status_message %}
{% if errors %}
<div class="alert alert-warning" role="alert">
{% trans "please, correct next errors!" %}
</div>
{% endif %}
{% endblock status_message %}
{% block content %}
<form enctype="multipart/form-data" class="form-horizontal"
{% if student %}
 action="{% url "students_edit" pk %}" 
 {% else %}
 action="{% url "s_add" %}"
 {% endif %}
 method="post">
    {% csrf_token %}
    <div class="form-group{% if errors.first_name %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "first name" %}*</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="form-control" name="first_name" id="first_name" value="{{student.first_name}}">
        {% else %}
           <input type="text" value="{{ request.POST.first_name }}"
           name="first_name" id="first_name" class="form-control" />
        {% endif %}
            <span class="help-block"> {{ errors.first_name }}</span>
        
        </div>
    </div>
    <div class="form-group{% if errors.last_name %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "last name" %}*</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="form-control" name="last_name" id="last_name" value="{{student.last_name}}">
        {% else %}
            <input type="text" value="{{ request.POST.last_name }}"
            name="last_name" id="last_name" class="form-control" /> 
        {% endif %}
            <span class="help-block"> {{ errors.last_name }}</span>
        </div>
    </div>
    
    <div class="form-group{% if errors.birthday %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "birthday" %}</label>
        <div class="col-sm-10">
        {% if student %}
            <input type="text" class="dateinput form-control" name="birthday" id="id_birthday" value="{{student.birthday|date:"Y-m-d"}}" >
        {% else %}
            <input type="text" class="dateinput form-control" value="{{ request.POST.birthday }}"
            name="birthday" id="birthday" class="form-control"
            placeholder="Напр. 1984-12-30" />
        {% endif %}
            <span class="help-block"> {{ errors.birthday }}</span>
        </div>
    </div>
    
    
    <div class="form-group{% if errors.student_group_id %} has-error{% endif %}">
        <label for="" class="control-label col-sm-2">{% trans "class" %}*</label>
        {% if student %}
        <div class="col-sm-10">
            <select class="form-control" name="student_group_id" id="student_group_id">
                <option value=""> {% trans "select class" %}</option>
                {% for group in groups %}
                    <option value="{{ group.id }}" {% if group.id == student.student_group_id.id %}selected="1"{% endif %}> {{ group.title }}</option>
                {% endfor %}
            </select>
            <span class="help-block"> {{ errors.student_group_id }}</span>
        </div>
        {% else %}
        <div class="col-sm-10">
           <select name="student_group_id" id="student_group_id" class="form-control"><option value="">{% trans "select group" %}</option>
           {% for group in groups %}
           <option value="{{ group.id }}" {% if group.id == request.POST.student_group_id|add:0 %}selected="1"{% endif %}>{{ group.title }}</option>
           {% endfor %}
           </select>
           <span class="help-block">{{ errors.student_group_id }}</span>
           </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2">{% trans "additional information" %}</label>
        {% if student %}
        <div class="col-sm-10">
            <textarea name="notes" id="notes" class="form-control">{{student.notes}}</textarea>
        </div>
        {% else %}
        <div class="col-sm-10">
          <textarea name="notes" id="notes" class="form-control"></textarea>
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label for="" class="control-label col-sm-2"></label>
        <div class="col-sm-10">
        {% if student %}
            <input class="btn btn-primary" type="submit" value="Зберегти" name="add_button"/>
            <button class="btn btn-link" type="submit" name="cancel_button">{% trans "cancel" %}</button>
        {% else %}
            <input type="submit" value="{% trans "add" %}" name="add_button"
            class="btn btn-primary" />
            <button type="submit" name="cancel_button"
            class="btn btn-link">{% trans "cancel" %}</button>
        {% endif %}
        </div>
    </div>
</form>
<div id="coments">
{% trans "Fields marked with an asterisk are obligatory for filling" %}
</div>
{% endblock content %}